	namespace eval post_cts_opt {variable post_cts_opt_cmd ""}
	set_param db save_all_params true
	set_param db max_read_liberty_thread 16  					
	set_param ta mcmm_mode auto
	set_param ta enable_crpr 1
	set_param ta crpr_mode normal
	set_param ta port_prop_clock_latency 1
	set_param ta median_port_latency true
	set_param ta propagated_clocks true
	set_param ta unset_ideal_clock_net true
	set_param ta set_ideal_clock_net false
	set_param route allow_cell_off_grid true
	set_param route avoid_double_via_lead 1
	set_param opt check_clock_drv 1
	set_param opt post_cts_clock_drc_opt 1
	set_param opt post_cts_opt_dont_worsen_drv auto
	set_param opt post_cts_area_opt 1
	set_param opt post_cts_power_opt 1
	set_param opt io_master_flow_ignore_hold 1
	set_param opt cts_opt_slack_margin 0.010
	set_param ta si_noise_effort hybrid
	set_param opt dont_create_assign true 
	set_param ta non_droute_use_receiver_ccsd_if_auto 1
	set_param opt hold_opt 1 
	set_param opt cts_opt_hold_slack_margin 0
	set_param opt skew_opt_hold false   
	set_param scan clock_tree_extra_effort 3
	set_param opt power_opt_effort MEDIUM
	set_param opt area_opt_effort MEDIUM
	set_param place use_metal_1_tracks 1
	set_param place use_vth_min_spacing_rules 1
	set_param route m1_bottom_ground_pm 1
	set_param ta crpr_threshold_in_ps 2.000
	puts "Finished loading cts_opt_params.tcl"
