set_param db no_routing_on_m0 0
set_param route dont_use_m0_wire false
#set_param route dont_use_m0_wire true
set_param route preserve_m0_layout false
set_param place avoid_cut0_violation 1
set_param place promote_short_m0_pins true
set_param place use_filler1_adjacent_rule 3
set_param route out_core_bndy_cell_flow 0
set_param route preserve_std_cell_m1_layout false
set_param place promote_short_m0_pins 1
#set_param place min_consecutive_access_m0 2
set_param place min_consecutive_access_m0 -1
set_param route out_core_bndy_cell_flow 0
